// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaJim_9SFEI4ZsWPwINFBlWswWMXs_6Mg',
    appId: '1:412840461291:web:872c8e8961d1e338ca8fae',
    messagingSenderId: '412840461291',
    projectId: 'iqfence',
    authDomain: 'iqfence.firebaseapp.com',
    databaseURL: 'https://iqfence-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iqfence.firebasestorage.app',
    measurementId: 'G-E11LMDY4G0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB1BWcnBiDbtg29w1zGPejOJ53XugXyHc',
    appId: '1:412840461291:android:c21d778c2f4ace14ca8fae',
    messagingSenderId: '412840461291',
    projectId: 'iqfence',
    databaseURL: 'https://iqfence-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iqfence.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-oB7shki3J_s1zcxSmqkqTvh2ibn_Y8c',
    appId: '1:412840461291:ios:91f8fec4b52b3f74ca8fae',
    messagingSenderId: '412840461291',
    projectId: 'iqfence',
    databaseURL: 'https://iqfence-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iqfence.firebasestorage.app',
    iosBundleId: 'com.example.iqfence',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-oB7shki3J_s1zcxSmqkqTvh2ibn_Y8c',
    appId: '1:412840461291:ios:91f8fec4b52b3f74ca8fae',
    messagingSenderId: '412840461291',
    projectId: 'iqfence',
    databaseURL: 'https://iqfence-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iqfence.firebasestorage.app',
    iosBundleId: 'com.example.iqfence',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaJim_9SFEI4ZsWPwINFBlWswWMXs_6Mg',
    appId: '1:412840461291:web:5f62e8934bada3faca8fae',
    messagingSenderId: '412840461291',
    projectId: 'iqfence',
    authDomain: 'iqfence.firebaseapp.com',
    databaseURL: 'https://iqfence-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iqfence.firebasestorage.app',
    measurementId: 'G-JWVRMZX4PQ',
  );
}
